### ISSUE TITLE
Handling special prices and grouped/bundle products for “ecomm_totalvalue”

### ISSUE THREAD

**Issue by sreichel** [sreichel/magento-Anaraky-GDRT#3]
See: https://www.kerstner.at/en/2015/08/fix-anaraky-google-dynamic-remarkting-tag-extension/

**Comment by marcuspitu** [comment]
I have the some problem. I did the things on this, but don´t work  https://www.kerstner.at/en/2015/08/fix-anaraky-google-dynamic-remarkting-tag-extension/.
My site: https://tecasistemas.com.br/dz-nano-rossi

**Comment by sreichel** [comment]
I've added patch from https://www.kerstner.at/en/2015/08/fix-anaraky-google-dynamic-remarkting-tag-extension/ and for me it works.

Can you please give me some more information?
