### ISSUE TITLE
Issue while installing it

### ISSUE THREAD

**Issue by miguelgamat** [sreichel/magento-Anaraky-GDRT#5]
Hi, thanks for this great extension, I have used it from Magento Connect and works great, but had some issue due it wasn't updated, so I wanted the latest version. I have installed it directly in my root folder, but I have some error after flushing cache.

Do you know why is this happening? Thanks in advance.
Miguel

**Comment by rvpatel** [comment]
yes, when old extension mysql data exits and override by this 
app\code\community\Anaraky\Gdrt\sql\anaraky_gdrt_setup\mysql4-install-1.0.9.1.php

thats time "google/gdrt_general/mail_template_ebay" multiple value update time constraint violation issue.

Manage manual in database & extra value deleted.

**Comment by sreichel** [comment]
Should be same as #8
