### ISSUE TITLE
ver. 1.9.2.3 For Which one use magento-connect / Git?

### ISSUE THREAD

**Issue by rvpatel** [sreichel/magento-Anaraky-GDRT#7]
I have using ver. 1.9.2.3 and now using a magento connect version.
This one working better then git version? please suggest which one we can use any error exits in git version?

2) For product page i can't found this 2 tags: (how we can manage?)

ecomm_category: '{category name}',
isSaleItem: false / true

3)  'var google_custom_params = window.google_tag_params;' . PHP_EOL 
   'var google_custom_params = google_tag_params;' . PHP_EOL 

which one right any difference?

**Comment by sreichel** [comment]
1. Version from Magento Connect was the official version. This one is just a fork with some small fixes.
2. Added tag in latest commit
3. Changed to `window.google_tag_params`, according to https://support.google.com/adwords/answer/3103357?hl=en
